application:
  goons:
    type: "alliance"
    id: 1354830081
    webhook_url: "https://discordapp.com/api/webhooks/403980105032138755/GOQoKsqwY7D6ZptcOkPNoDNfxTkE7uO2dfn4QUdAjvUuNQnqqlKhvwLmw3BB14J2xubz"
    processing:
      type: 'victim'
      min_isk_lost: 500000000
