application:
  goons:
    type: "alliance"
    id: 1354830081
    webhook_url: "https://discordapp.com/api/webhooks/404059288126881802/8vYqqubSSIE9q2Ar_DBAyywETsMAYUgRtQz-GhNmwFBbH04qKNckJqix4TYo9RXfaHtx"
    processing:
      type: 'victim'
      attackers:
        - 98540683